language: c
addons:
  apt:
    packages:
      - qemu-user-static
      - proot
cache:
  directories:
    - packages
    - rootfs
env:
  - ARCH=x86_64
  - ARCH=arm
  - ARCH=armv6h
  - ARCH=armv7h
  - ARCH=aarch64
script:
  - bash arch-bootstrap.sh -a $ARCH -d packages/$ARCH rootfs/$ARCH