language: generic
sudo: required
dist: trusty
notifications:
  email: false
before_install:
  - DEBIAN_FRONTEND=noninteractive sudo apt-get install -y qemu-user-static
  - DEBIAN_FRONTEND=noninteractive sudo apt-get install -y bsdtar
cache:
  directories:
    - packages
    - rootfs
env:
  - ARCH=x86_64
  - ARCH=arm
  - ARCH=armv6h
  - ARCH=armv7h
  - ARCH=aarch64
script:
  - sudo bash arch-bootstrap.sh -a $ARCH -d packages/$ARCH rootfs/$ARCH
